//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GradesDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblResult
    {
        public int ID { get; set; }
        public string ExamID { get; set; }
        public string Name { get; set; }
        public int Score { get; set; }
        public int ItemOne { get; set; }
        public int ItemTwo { get; set; }
    }
}
